name: Test Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.TEST_VERCEL_PROJECT_ID }}
  DOMAIN_URL: ${{ secrets.TEST_DOMAIN_URL }}

on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10 # 设置作业的超时时间为 10 分钟，可根据需要自行调整

    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Build Project Artifacts
        run: vercel build --prod --local-config ./vercel.json --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Handle special characters in commit message
        run: |
          echo "SAFE_COMMIT_MESSAGE=$(git log -1 --pretty=%B | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g' | sed "s/'/\\'/g")" >> $GITHUB_ENV